### ISSUE TITLE
Add pages (including homepage)

### ISSUE THREAD

**Issue by nplhse** [nplhse/arcella#1]
Add CRUD operations for Page entities with static urls (without nesting), including a "special" homepage.

**Todo:**
- [x] Create Page entity
- [x] Create PageController
- [x] Create "special" DefaultController for the homepage
- [x] Create backend for CRUD operations on Page entities

**Comment by nplhse** [comment]
Done!
