### ISSUE TITLE
Add "dashboard" to backend

### ISSUE THREAD

**Issue by nplhse** [nplhse/arcella#11]
There should be some kind of "dashboard" for the backend. It's not a very nice experience for users/ admins to land directly in the list view of an entity...

**Todo**

- [ ] Add basic "dashboard" for the backend
- [ ] Add some basic statistics to the backend
- [ ] Add links for common actions
