### ISSUE TITLE
Add basic users

### ISSUE THREAD

**Issue by nplhse** [nplhse/arcella#3]
Add CRUD operations for User entities with login/ logout and registration

**Todo:**
- [x] Create User entity
- [x] Create User workflow with Command+ Handlers for registration
- [x] Create SecurityController for login/ logout
- [x] Create UserController for the registration
- [x] Create backend for CRUD operations on User entities 

**Update (12.02.2018):** 
Here are some now Todos resulting from the current work:
- [x] Add events to the User workflows
- [x] Add form validation to the registration

**Comment by nplhse** [comment]
Here are some now Todos resulting from the current work:

- [ ] Add events to the User workflows
- [ ] Add form validation to the registration

**Comment by nplhse** [comment]
Finally finished this part of the development! \o/
